package(
    default_visibility = ["//tensorflow_serving:internal"],
)

filegroup(
    name = "py_layers",
    srcs = [
        "py_layers/00000001/deploy.prototxt",
        "py_layers/00000001/test_python_layer.py",
        "py_layers/00000001/weights.caffemodel",
    ],
)
